# Generated by Django 5.1.6 on 2025-03-07 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_file_tag_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='file_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.file'),
            preserve_default=False,
        ),
    ]
