# Generated by Django 5.1.6 on 2025-03-07 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tag_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='file_name',
            new_name='file_id',
        ),
    ]
