# Generated by Django 5.1.6 on 2025-03-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_file_name_tag_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='old_tag_regex',
            field=models.CharField(default='', max_length=80),
        ),
    ]
