# Generated by Django 5.1.6 on 2025-03-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tag_old_tag_regex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='new_tag',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
